require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/**/*
    - bin/**/*
    - ruby/**/*

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false
